#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#
# Get function from functions library

. /etc/init.d/functions

if [ -f /etc/sysconfig/play ]; then
    . /etc/sysconfig/play
fi

prog=cloudify-widget
pidfile=${PIDFILE-$WIDGET_HOME/RUNNING_PID}


# Start the service FOO
start() {
#        initlog -c "echo -n Starting Widget server: "
        cd $WIDGET_HOME
        ./play_start.sh
        success $"Widget server startup"
        echo
}
# Restart the service FOO
stop() {
#        initlog -c "echo -n Stopping Widget server: "
        killproc -p $pidfile
        echo
}

executeScript(){
    cd $WIDGET_HOME/conf
    node scriptsExecutor.js >> $WIDGET_HOME/logs/scriptsExecutor.log 2>&1
}

upgrade(){
#    initlog -c "echo -n Upgrading Widget server: "
    cd $WIDGET_HOME
    ./upgrade_server.sh
    success $"Widget server upgraded"
    echo
}
tail(){
    cd $WIDGET_HOME
    tail -f nohup.out
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p ${pidfile}
        ;;
  upgrade)
        upgrade
        ;;
  executeScript)
        executeScript
        ;;
  tail)
        tail
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status|upgrade|executeScript}"
        exit 1
esac
exit 0
